# Generated by Django 2.0.7 on 2018-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20181018_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_empty',
            field=models.BooleanField(choices=[(True, 'Empty'), (False, 'Not Empty')], default=1),
        ),
    ]
